app:
  name: myapp_saltmaster
  port: 443
  path: /opt/app
  config_name: app-saltmaster
  comment: host config
  enable_firewall: True
  token: {{ salt['pillar.get']('ad_pwd', None) }}

user:
  name: svc_appuser
  disable: False

banner:
  name: App is Live
